// import { createElement } from 'lwc';
// import Parent2ChildNonPrimitivesChild1 from 'c/parent2ChildNonPrimitivesChild1';

// describe('c-parent2-child-non-primitives-child1', () => {
//     afterEach(() => {
//         // The jsdom instance is shared across test cases in a single file so reset the DOM
//         while (document.body.firstChild) {
//             document.body.removeChild(document.body.firstChild);
//         }
//     });

//     it('TODO: test case generated by CLI command, please fill in test logic', () => {
//         // Arrange
//         const element = createElement('c-parent2-child-non-primitives-child1', {
//             is: Parent2ChildNonPrimitivesChild1
//         });

//         // Act
//         document.body.appendChild(element);

//         // Assert
//         // const div = element.shadowRoot.querySelector('div');
//         expect(1).toBe(1);
//     });
// });