
date newDate = date.today();
Boolean result = Calculator.leapYearCheck(newDate);
system.debug(result);

integer addResult = Calculator.add(40,50);
system.debug('sum is ='+ addResult);

integer addResult2 = Calculator.add(40,40);
system.debug('sum is ='+ addResult2);

integer subtractResult = Calculator.subtract(388,23);
system.debug('result is = ' + subtractResult);

integer multipleResult = Calculator.multiple(4, 5);
System.debug('result is = ' + multipleResult);