
Candidate.printCandidateInfo();

Candidate.CompanyName='nhs';

Candidate person1 = new Candidate();
person1.name='ridvan';
person1.gender='male';
person1.printCandidate();


Candidate person2 = new Candidate();
person2.name='ezgi';
person2.gender='female';
person2.printCandidate();

Candidate.CompanyName='jbl';
Candidate person3 = new Candidate();
person3.name='bebis';
person3.gender='female';
person3.printCandidate();

