
Map<String,email_domain__mdt> allEmailDomains = email_domain__mdt.getAll();
system.debug(allEmailDomains);


{Gmail=Email_Domain__mdt:{Domain__c=Gmail, Label=Gmail, MasterLabel=Gmail, SystemModstamp=2023-05-15 13:37:26, Language=en_US, QualifiedApiName=Gmail, Id=m008d000000OZY5, DeveloperName=Gmail, NamespacePrefix=null}, 

Hotmail=Email_Domain__mdt:{Domain__c=Hotmail, Label=Hotmail, MasterLabel=Hotmail, SystemModstamp=2023-05-15 13:37:45, Language=en_US, QualifiedApiName=Hotmail, Id=m008d000000OZYA, DeveloperName=Hotmail, NamespacePrefix=null}}