RankHandler prizeSelector = new RankHandler();

// string prize1 =prizeSelector.rankPrize(1);
// system.debug(prize1);


// string prize4 =prizeSelector.rankPrize(4);
// system.debug(prize4);


// string prize16 =prizeSelector.rankPrize(16);
// system.debug(prize16);


string prize1 =prizeSelector.getRankPrize(1);
system.debug(prize1);


string prize4 =prizeSelector.getRankPrize(4);
system.debug(prize4);


string prize16 =prizeSelector.getRankPrize(16);
system.debug(prize16);