// HttpResponse res= RESTCallouts.getAnimals();
// HttpResponse response2= RESTCallouts.getUsers();
// System.debug(response2);

// HttpResponse response3= RESTCallouts.getProducts();
// System.debug(response3);

// HttpResponse response4= RESTCallouts.getBlog();
// System.debug(response4);

//post request
// PostCallout.postMethod();


//test post userst//
HttpResponse response4= RESTCallouts.postContacts();
System.debug(response4);

